
version: '3.9'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.11
    container_name: etcd
    command: >
      /usr/local/bin/etcd         --name etcd0         --data-dir /etcd-data         --initial-advertise-peer-urls http://etcd:2380         --listen-peer-urls http://0.0.0.0:2380         --listen-client-urls http://0.0.0.0:2379         --advertise-client-urls http://etcd:2379         --initial-cluster etcd0=http://etcd:2380         --initial-cluster-token patroni-cluster         --initial-cluster-state new
    ports:
      - "2379:2379"
    networks:
      - patroni-net
    volumes:
      - etcd-data:/etcd-data

  patroni-1:
    image: zalando/patroni:3.2.2
    container_name: patroni-1
    environment:
      - PATRONI_NAME=patroni-1
      - PATRONI_SCOPE=postgres-cluster
      - PATRONI_ETCD_HOSTS=etcd:2379
      - PATRONI_REST_API_LISTEN=0.0.0.0:8008
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni-1:5432
      - PATRONI_POSTGRESQL_USERNAME=postgres
      - PATRONI_POSTGRESQL_PASSWORD=postgres
    volumes:
      - ./patroni/patroni-1.yml:/config/patroni.yml
      - ./patroni/pg_hba.conf:/pg_hba.conf
      - ./data/patroni-1:/var/lib/postgresql/data
    networks:
      - patroni-net
    ports:
      - "5432:5432"
      - "8008:8008"
    command: ["/bin/sh", "-c", "PATRONI_CONFIG_FILE=/config/patroni.yml patroni"]

  patroni-2:
    image: zalando/patroni:3.2.2
    container_name: patroni-2
    environment:
      - PATRONI_NAME=patroni-2
      - PATRONI_SCOPE=postgres-cluster
      - PATRONI_ETCD_HOSTS=etcd:2379
      - PATRONI_REST_API_LISTEN=0.0.0.0:8008
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni-2:5432
      - PATRONI_POSTGRESQL_USERNAME=postgres
      - PATRONI_POSTGRESQL_PASSWORD=postgres
    volumes:
      - ./patroni/patroni-2.yml:/config/patroni.yml
      - ./patroni/pg_hba.conf:/pg_hba.conf
      - ./data/patroni-2:/var/lib/postgresql/data
    networks:
      - patroni-net
    ports:
      - "5433:5432"
      - "8009:8008"
    command: ["/bin/sh", "-c", "PATRONI_CONFIG_FILE=/config/patroni.yml patroni"]

  patroni-3:
    image: zalando/patroni:3.2.2
    container_name: patroni-3
    environment:
      - PATRONI_NAME=patroni-3
      - PATRONI_SCOPE=postgres-cluster
      - PATRONI_ETCD_HOSTS=etcd:2379
      - PATRONI_REST_API_LISTEN=0.0.0.0:8008
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni-3:5432
      - PATRONI_POSTGRESQL_USERNAME=postgres
      - PATRONI_POSTGRESQL_PASSWORD=postgres
    volumes:
      - ./patroni/patroni-3.yml:/config/patroni.yml
      - ./patroni/pg_hba.conf:/pg_hba.conf
      - ./data/patroni-3:/var/lib/postgresql/data
    networks:
      - patroni-net
    ports:
      - "5434:5432"
      - "8010:8008"
    command: ["/bin/sh", "-c", "PATRONI_CONFIG_FILE=/config/patroni.yml patroni"]

  redis:
    image: redis:7.2
    container_name: redis
    networks:
      - patroni-net
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    networks:
      - patroni-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  etcd-data:
  pgadmin-data:

networks:
  patroni-net:
    driver: bridge
